-- MySQL Script generated by MySQL Workbench
-- Sun May  7 17:36:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BOOKING
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BOOKING
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BOOKING` DEFAULT CHARACTER SET utf8 ;
USE `BOOKING` ;

-- -----------------------------------------------------
-- Table `BOOKING`.`HOTEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOKING`.`HOTEL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ROOM_ID` INT NULL,
  `MANAGER_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BOOKING`.`ROOM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOKING`.`ROOM` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `BOOKING_ID` INT NULL,
  `HOTEL_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ROOM_ID_UNIQUE` (`ID` ASC),
  INDEX `fk_ROOM_HOTEL_idx` (`HOTEL_ID` ASC),
  CONSTRAINT `fk_ROOM_HOTEL`
    FOREIGN KEY (`HOTEL_ID`)
    REFERENCES `BOOKING`.`HOTEL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BOOKING`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOKING`.`ROLES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `STATUS` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ROLES_ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BOOKING`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOKING`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `LOGIN` VARCHAR(20) NOT NULL,
  `PASSWORD` VARCHAR(20) NOT NULL,
  `ROLES_ID` INT NOT NULL,
  `HOTEL_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `ROLES_ID`),
  INDEX `fk_USER_ROLES1_idx` (`ROLES_ID` ASC),
  INDEX `fk_USER_HOTEL1_idx` (`HOTEL_ID` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  CONSTRAINT `fk_USER_ROLES1`
    FOREIGN KEY (`ROLES_ID`)
    REFERENCES `BOOKING`.`ROLES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_HOTEL1`
    FOREIGN KEY (`HOTEL_ID`)
    REFERENCES `BOOKING`.`HOTEL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BOOKING`.`BOOKING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOKING`.`BOOKING` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATE` DATE NULL,
  `ROOM_ID` INT NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `BOOKING_ID_UNIQUE` (`ID` ASC),
  INDEX `fk_BOOKING_ROOM1_idx` (`ROOM_ID` ASC),
  INDEX `fk_BOOKING_USER1_idx` (`USER_ID` ASC),
  CONSTRAINT `fk_BOOKING_ROOM1`
    FOREIGN KEY (`ROOM_ID`)
    REFERENCES `BOOKING`.`ROOM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BOOKING_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `BOOKING`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
