-- MySQL Script generated by MySQL Workbench
-- Wed Mar 22 00:51:22 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myHotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myHotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myHotel` DEFAULT CHARACTER SET utf8 ;
USE `myHotel` ;

-- -----------------------------------------------------
-- Table `myHotel`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myHotel`.`booking` (
  `bookingId` INT NOT NULL,
  `date` DATETIME NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`bookingId`),
  UNIQUE INDEX `bookingId_UNIQUE` (`bookingId` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myHotel`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myHotel`.`room` (
  `roomId` INT NOT NULL,
  `booking_bookingId` INT NOT NULL,
  PRIMARY KEY (`roomId`),
  UNIQUE INDEX `roomId_UNIQUE` (`roomId` ASC),
  INDEX `fk_room_booking1_idx` (`booking_bookingId` ASC),
  CONSTRAINT `fk_room_booking1`
    FOREIGN KEY (`booking_bookingId`)
    REFERENCES `myHotel`.`booking` (`bookingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myHotel`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myHotel`.`user` (
  `userId` INT NOT NULL,
  `level` ENUM('ADMIN', 'MANAGER', 'TOURIST') NULL COMMENT 'admin\nmanager\ntourist',
  `login` VARCHAR(20) NULL,
  `password` VARCHAR(20) NULL,
  `fio` VARCHAR(100) NULL,
  `booking_bookingId` INT NOT NULL,
  `hotel_hotelId` INT NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC),
  INDEX `fk_user_booking1_idx` (`booking_bookingId` ASC),
  INDEX `fk_user_hotel1_idx` (`hotel_hotelId` ASC),
  CONSTRAINT `fk_user_booking1`
    FOREIGN KEY (`booking_bookingId`)
    REFERENCES `myHotel`.`booking` (`bookingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_hotel1`
    FOREIGN KEY (`hotel_hotelId`)
    REFERENCES `myHotel`.`hotel` (`hotelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myHotel`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myHotel`.`hotel` (
  `hotelId` INT NOT NULL,
  `info` VARCHAR(100) NULL,
  `room_roomId` INT NOT NULL,
  `user_userId` INT NOT NULL,
  UNIQUE INDEX `hotelId_UNIQUE` (`hotelId` ASC),
  PRIMARY KEY (`hotelId`),
  INDEX `fk_hotel_room1_idx` (`room_roomId` ASC),
  INDEX `fk_hotel_user1_idx` (`user_userId` ASC),
  CONSTRAINT `fk_hotel_room1`
    FOREIGN KEY (`room_roomId`)
    REFERENCES `myHotel`.`room` (`roomId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hotel_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `myHotel`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
