-- MySQL Script generated by MySQL Workbench
-- Sat Mar 18 00:30:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myHotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myHotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myHotel` DEFAULT CHARACTER SET utf8 ;
USE `myHotel` ;

-- -----------------------------------------------------
-- Table `myHotel`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myHotel`.`booking` (
  `bookingId` INT NOT NULL,
  `date` DATETIME NULL,
  `userId` INT NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`bookingId`),
  UNIQUE INDEX `bookingId_UNIQUE` (`bookingId` ASC),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myHotel`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myHotel`.`room` (
  `roomId` INT NOT NULL,
  `hotelId` INT NULL,
  `bookingId` INT NULL,
  PRIMARY KEY (`roomId`),
  UNIQUE INDEX `roomId_UNIQUE` (`roomId` ASC),
  UNIQUE INDEX `hotelId_UNIQUE` (`hotelId` ASC),
  UNIQUE INDEX `bookingId_UNIQUE` (`bookingId` ASC),
  CONSTRAINT `room_booking`
    FOREIGN KEY (`bookingId`)
    REFERENCES `myHotel`.`booking` (`bookingId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myHotel`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myHotel`.`hotel` (
  `hotelId` INT NOT NULL,
  `userId` INT NULL,
  `roomId` INT NULL,
  `info` VARCHAR(100) NULL,
  UNIQUE INDEX `hotelId_UNIQUE` (`hotelId` ASC),
  PRIMARY KEY (`hotelId`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC),
  UNIQUE INDEX `roomId_UNIQUE` (`roomId` ASC),
  CONSTRAINT `hotel_room`
    FOREIGN KEY (`roomId`)
    REFERENCES `myHotel`.`room` (`roomId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `myHotel`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myHotel`.`user` (
  `userId` INT NOT NULL,
  `level` VARCHAR(10) NULL COMMENT 'admin\nmanager\ntourist',
  `login` VARCHAR(20) NULL,
  `password` VARCHAR(20) NULL,
  `fio` VARCHAR(100) NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC),
  CONSTRAINT `user_booking`
    FOREIGN KEY (`userId`)
    REFERENCES `myHotel`.`booking` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_hotel`
    FOREIGN KEY (`userId`)
    REFERENCES `myHotel`.`hotel` (`hotelId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
